Style/StringLiterals:
  Enabled: false

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Style/Documentation:
  Enabled: false

Lint/EmptyMethod:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 100

AllCops:
  Exclude:
    - "db/schema.rb"
    - "db/migrate/*.rb"
